server:
  port: 8083
  
spring:
  application:
    name: sujog-migration
  profiles:
    include:
    - lookup
app:
  timezone: UTC

file:
  path:
    input:
      directory: 
        property: /home/obpsdev/Documents/Migrate_Data/Property/Instance1/File
        wns: /home/obpsdev/Documents/Migrate_Data/Wns/Instance1/File
    output:
      property:
        success: /home/obpsdev/Documents/Migrate_Data/Property/Instance1/Success
        error: /home/obpsdev/Documents/Migrate_Data/Property/Instance1/Error
      wns:
        success: /home/obpsdev/Documents/Migrate_Data/Wns/Instance1/Success
        error: /home/obpsdev/Documents/Migrate_Data/Wns/Instance1/Error
    
remomte:
  api:
    auth:
      url: http://sujog.odisha.gov.in/user/oauth/token
      username: admin
      password: password
      tenant: od
    pt:
      host: http://sujog.odisha.gov.in/property-services
      search: /property/_search
      migrate: /property/_migrateproperty
      migrateuser: /property/_migratepropertyuser
      asmt:
        search: /assessment/_search
        migrate: /assessment/_migrateassessment
    ws:
      host: http://sujog.odisha.gov.in/ws-services/wc
      search: /_search
      connectionmigrate: /_migrate
      calculator:
        host: http://sujog.odisha.gov.in/ws-calculator
        meterreadingmigeate: /meterConnection/_migrateMeterReading
        meterreadingsearch: /meterConnection/_search
        demandmigrate: /waterCalculator/_migrateDemand
    sw:
      host: http://sujog.odisha.gov.in/sw-services/swc
      search: /_search
      connectionmigrate: /_migrate
      calculator:
        host: http://sujog.odisha.gov.in/sw-calculator/sewerageCalculator
        demandmigrate: /_migrateDemand
    demand:
      host: http://sujog.odisha.gov.in/billing-service
      search: /demand/_search
      fetchbill: /bill/v2/_fetchbill

      