server:
  port: 9090
  
spring:
  application:
    name: sujog-migration
  profiles:
    include:
    - lookup
app:
  timezone: UTC

file:
  path:
    input:
      directory: 
        property: C:\Users\prasunAdmin\Desktop\Tasks\Migration\Batch_file\Files\property
        wns: C:\Users\prasunAdmin\Desktop\Tasks\Migration\Batch_file\Files\wns
    output:
      property:
        success: C:\Users\prasunAdmin\Desktop\Tasks\Migration\Batch_file\Success\property
        error: C:\Users\prasunAdmin\Desktop\Tasks\Migration\Batch_file\Error\property
      wns:
        success: C:\Users\prasunAdmin\Desktop\Tasks\Migration\Batch_file\Success\wns
        error: C:\Users\prasunAdmin\Desktop\Tasks\Migration\Batch_file\Error\wns
    
remomte:
  api:
    auth:
      url: http://localhost:8083/user/oauth/token
      username: admin
      password: password
      tenant: od
    pt:
      host: http://localhost:8083/property-services
      search: /property/_search
      migrate: /property/_migrateproperty
      migrateuser: /property/_migratepropertyuser
      asmt:
        search: /assessment/_search
        migrate: /assessment/_migrateassessment
    ws:
      host: http://localhost:8083/ws-services/wc
      search: /_search
      connectionmigrate: /_migrate
      calculator:
        host: http://localhost:8083/ws-calculator
        meterreadingmigeate: /meterConnection/_migrateMeterReading
        meterreadingsearch: /meterConnection/_search
        demandmigrate: /waterCalculator/_migrateDemand
    sw:
      host: http://localhost:8083/sw-services/swc
      search: /_search
      connectionmigrate: /_migrate
      calculator:
        host: http://localhost:8083/sw-calculator/sewerageCalculator
        demandmigrate: /_migrateDemand
    demand:
      host: http://localhost:8083/billing-service
      search: /demand/_search
      fetchbill: /bill/v2/_fetchbill
      update: /demand/_updatedemanddetails

      
