masterdata:
  taxhead:
    holding_tax: PT_HOLDING_TAX
    light: PT_LIGHT_TAX
    service_tax: PT_SERVICE_TAX
    street_tax: PT_LIGHT_TAX
    water_tax: PT_WATER_TAX
    light_tax: PT_LIGHT_TAX
    drainage_tax: PT_DRAINAGE_TAX
    latrine_tax: PT_LATRINE_TAX
    parking_tax: PT_PARKING_TAX
    solid_waste_user_charges: PT_SOLID_WASTE_USER_CHARGES
    ownership_excemption: PT_OWNERSHIP_EXCEMPTION
    usage_excemption: PT_USAGE_EXCEMPTION
    interest: PT_INTEREST
    penalty: PT_PENALTY
    other: PT_OTHER_DUES
    drain_tax: PT_DRAINAGE_TAX
    house_tax: PT_HOLDING_TAX
    latin_tax: PT_LATRINE_TAX
    latrin_tax: PT_LATRINE_TAX
    street_light: PT_LIGHT_TAX
    holdging_tax: PT_HOLDING_TAX
    o: PT_OTHER_DUES
    
  tenants:
    cuttack: od.cuttack
    jatni: od.jatni
    angul: od.angul
    choudwar: od.choudwar
    berhampurdevelopmentauthority: od.berhampurdevelopmentauthority
    birmitrapur: od.birmitrapur
    berhampur: od.berhampur
    chatrapur: od.chatrapur
    cuttackdevelopmentauthority: od.cuttackdevelopmentauthority
    gopalpur: od.gopalpur
    kalinganagardevelopmentauthority: od.kalinganagardevelopmentauthority
    khordha: od.khordha
    konark: od.konark
    paradeep: od.paradeep
    paradipdevelopmentauthority: od.paradipdevelopmentauthority
    puri: od.puri
    purikonarkdevelopmentauthority: od.purikonarkdevelopmentauthority
    rajgangpur: od.rajgangpur
    rourkela: od.rourkela
    rourkeladevelopmentauthority: od.rourkeladevelopmentauthority
    sambalpur: od.sambalpur
    sambalpurdevelopmentauthority: od.sambalpurdevelopmentauthority
    sundargarh: od.sundargarh
    talcher: od.talcher
    talcherangulmeramandalidevelopmentauthority: od.talcherangulmeramandalidevelopmentauthority
    vyasanagar: od.vyasanagar
    anandapur: od.anandapur
    aska: od.aska
    athagarh: od.athagarh
    athmallik: od.athmallik
    attabira: od.attabira
    balangir: od.balangir
    balasore: od.balasore
    balimela: od.balimela
    balliguda: od.balliguda
    balugaon: od.balugaon
    banki: od.banki
    banpur: od.banpur
    bargarh: od.bargarh
    barbil: od.barbil
    baripada: od.baripada
    barpali: od.barpali
    basudevpur: od.basudevpur
    bellaguntha: od.bellaguntha
    belpahar: od.belpahar
    bhadrak: od.bhadrak
    bhanjanagar: od.bhanjanagar
    bhawanipatna: od.bhawanipatna
    bhuban: od.bhuban
    bijepur: od.bijepur
    binka: od.binka
    boudhgarh: od.boudhgarh
    brajrajnagar: od.brajrajnagar
    buguda: od.buguda
    champua: od.champua
    chandbali: od.chandbali
    chikiti: od.chikiti
    daspalla: od.daspalla
    deogarh: od.deogarh
    dhamnagar: od.dhamnagar
    dharamgarh: od.dharamgarh
    dhenkanal: od.dhenkanal
    digapahandi: od.digapahandi
    gudayagiri: od.gudayagiri
    ganjam: od.ganjam
    gudari: od.gudari
    gunupur: od.gunupur
    hindol: od.hindol
    hinjilicut: od.hinjilicut
    jagatsinghpur: od.jagatsinghpur
    jajpur: od.jajpur
    jaleswar: od.jaleswar
    jeypore: od.jeypore
    jharsuguda: od.jharsuguda
    joda: od.joda
    junagarh: od.junagarh
    kamakhyanagar: od.kamakhyanagar
    kantabanji: od.kantabanji
    karanjia: od.karanjia
    kashinagar: od.kashinagar
    kabisuryanagar: od.kabisuryanagar
    kendrapara: od.kendrapara
    keonjhargarh: od.keonjhargarh
    kesinga: od.kesinga
    khallikote: od.khallikote
    khandapada: od.khandapada
    khariar: od.khariar
    khariarroad: od.khariarroad
    kodala: od.kodala
    koraput: od.koraput
    kotpad: od.kotpad
    kuchinda: od.kuchinda
    malkangiri: od.malkangiri
    nayagarh: od.nayagarh
    nilgiri: od.nilgiri
    nimapara: od.nimapara
    nabarangpur: od.nabarangpur
    nuapada: od.nuapada
    odagaon: od.odagaon
    padampur: od.padampur
    paralakhemundi: od.paralakhemundi
    patnagarh: od.patnagarh
    pattamundai: od.pattamundai
    phulbani: od.phulbani
    pipli: od.pipli
    polasara: od.polasara
    purushottampur: od.purushottampur
    rairangpur: od.rairangpur
    rambha: od.rambha
    ranpur: od.ranpur
    rayagada: od.rayagada
    redhakhol: od.redhakhol
    sonepur: od.sonepur
    soro: od.soro
    surada: od.surada
    sunabeda: od.sunabeda
    tarbha: od.tarbha
    titilagarh: od.titilagarh
    tusura: od.tusura
    udala: od.udala
    umerkote: od.umerkote
    
  localitycode:
    cuttack: VIL84
    jatni: VIL12
    angul: VIL4
    choudwar: VIL23
    berhampurdevelopmentauthority: VIL92
    birmitrapur: VIL6
    berhampur: VIL40
    chatrapur: VIL10
    cuttackdevelopmentauthority: VIL53
    gopalpur: VIL5
    kalinganagardevelopmentauthority: VIL142
    khordha: VIL13
    konark: VIL9
    paradeep: VIL3
    paradipdevelopmentauthority: VIL19
    puri: VIL35
    purikonarkdevelopmentauthority: VIL75
    rajgangpur: VIL7
    rourkela: VIL53
    rourkeladevelopmentauthority: VIL55
    sambalpur: VIL46
    sambalpurdevelopmentauthority: VIL64
    sundargarh: VIL6
    talcher: VIL17
    talcherangulmeramandalidevelopmentauthority: VIL579
    vyasanagar: VIL21
    anandapur: VIL9
    aska: VIL6
    athagarh: VIL12
    athmallik: VIL15
    attabira: VIL7
    balangir: VIL8
    balasore: VIL29
    balimela: VIL2
    balliguda: VIL5
    balugaon: VIL7
    banki: VIL8
    banpur: VIL23
    bargarh: VIL4
    barbil: VIL12
    baripada: VIL20
    barpali: VIL4
    basudevpur: VIL20
    bellaguntha: VIL4
    belpahar: VIL5
    bhadrak: VIL21
    bhanjanagar: VIL3
    bhawanipatna: VIL7
    bhuban: VIL26
    bijepur: VIL7
    binka: VIL17
    boudhgarh: VIL4
    brajrajnagar: VIL4
    buguda: VIL8
    champua: VIL8
    chandbali: VIL25
    chikiti: VIL6
    daspalla: VIL11
    deogarh: VIL11
    dhamnagar: VIL8
    dharamgarh: VIL5
    dhenkanal: VIL13
    digapahandi: VIL4
    gudayagiri: VIL8
    ganjam: VIL3
    gudari: VIL4
    gunupur: VIL12
    hindol: VIL15
    hinjilicut: VIL5
    jagatsinghpur: VIL19
    jajpur: VIL86
    jaleswar: VIL18
    jeypore: VIL9
    jharsuguda: VIL10
    joda: VIL6
    junagarh: VIL3
    kamakhyanagar: VIL6
    kantabanji: VIL4
    karanjia: VIL10
    kashinagar: VIL2
    kabisuryanagar: VIL9
    kendrapara: VIL37
    keonjhargarh: VIL25
    kesinga: VIL5
    khallikote: VIL4
    khandapada: VIL6
    khariar: VIL14
    khariarroad: VIL20
    kodala: VIL4
    koraput: VIL11
    kotpad: VIL3
    kuchinda: VIL7
    malkangiri: VIL7
    nayagarh: VIL13
    nilgiri: VIL14
    nimapara: VIL6
    nabarangpur: VIL4
    nuapada: VIL9
    odagaon: VIL9
    padampur: VIL2
    paralakhemundi: VIL7
    patnagarh: VIL3
    pattamundai: VIL16
    phulbani: VIL14
    pipli: VIL14
    polasara: VIL9
    purushottampur: VIL4
    rairangpur: VIL10
    rambha: VIL3
    ranpur: VIL9
    rayagada: VIL10
    redhakhol: VIL19
    sonepur: VIL5
    soro: VIL21
    surada: VIL3
    sunabeda: VIL8
    tarbha: VIL7
    titilagarh: VIL3
    tusura: VIL14
    udala: VIL13
    umerkote: VIL7
    
  floorNo:
    ground_floor: 0
    first_floor: 1
    second_floor: 2
    third_floor: 3
    forth_floor: 4
    fifth_floor: 5
    sixth_floor: 6
    seventh_floor: 7
    eighth_floor: 8
    
    