server:
  port: 8083
  
spring:  application:    name: sujog-migration
  profiles:    include:    - lookup
app:
  timezone: UTC

file:
  path:
    input:
      directory: 
        property: /home/obpsdev/Documents/Migrate_Data/Property/Files
        wns: C:\Users\prasunAdmin\Desktop\Tasks\Migration\Batch_file\Files\wns
    output:
      property:
        success: /home/obpsdev/Documents/Migrate_Data/Property/Success
        error: /home/obpsdev/Documents/Migrate_Data/Property/Error
      wns:
        success: C:\Users\prasunAdmin\Desktop\Tasks\Migration\Batch_file\Success\wns
        error: C:\Users\prasunAdmin\Desktop\Tasks\Migration\Batch_file\Error\wns
    
remomte:
  api:
    auth:
      url: https://sujog-dev.odisha.gov.in/user/oauth/token
      username: hr_admin1
      password: Od@123456
      tenant: od.cuttack
    pt:
      host: https://sujog-dev.odisha.gov.in/property-services
      search: /property/_search
      migrate: /property/_migrateproperty
      asmt:
        search: /assessment/_search
        migrate: /assessment/_migrateassessment
      
