masterdata:
  taxhead:
    holding_tax: PT_HOLDING_TAX
    light: PT_LIGHT_TAX
    service_tax: PT_SERVICE_TAX
    street_tax: PT_OTHER_DUES
    water_tax: PT_WATER_TAX
    light_tax: PT_LIGHT_TAX
    drainage_tax: PT_DRAINAGE_TAX
    latrine_tax: PT_LATRINE_TAX
    parking_tax: PT_PARKING_TAX
    solid_waste_user_charges: PT_SOLID_WASTE_USER_CHARGES
    ownership_excemption: PT_OWNERSHIP_EXCEMPTION
    usage_excemption: PT_USAGE_EXCEMPTION
    interest: PT_INTEREST
    penalty: PT_PENALTY
    other: PT_OTHER_DUES
    
  tenants:
    cuttack: od.cuttack
    jatni: od.jatni
    angul: od.angul
    choudwar: od.choudwar
    berhampurdevelopmentauthority: od.berhampurdevelopmentauthority
    birmitrapur: od.birmitrapur
    berhampur: od.berhampur
    chatrapur: od.chatrapur
    cuttackdevelopmentauthority: od.cuttackdevelopmentauthority
    gopalpur: od.gopalpur
    kalinganagardevelopmentauthority: od.kalinganagardevelopmentauthority
    khordha: od.khordha
    konark: od.konark
    paradeep: od.paradeep
    paradipdevelopmentauthority: od.paradipdevelopmentauthority
    puri: od.puri
    purikonarkdevelopmentauthority: od.purikonarkdevelopmentauthority
    rajgangpur: od.rajgangpur
    rourkela: od.rourkela
    rourkeladevelopmentauthority: od.rourkeladevelopmentauthority
    sambalpur: od.sambalpur
    sambalpurdevelopmentauthority: od.sambalpurdevelopmentauthority
    sundargarh: od.sundargarh
    talcher: od.talcher
    talcherangulmeramandalidevelopmentauthority: od.talcherangulmeramandalidevelopmentauthority
    vyasanagar: od.vyasanagar
    anandapur: od.anandapur
    aska: od.aska
    athagarh: od.athagarh
    athmallik: od.athmallik
    attabira: od.attabira
    balangir: od.balangir
    balasore: od.balasore
    balimela: od.balimela
    balliguda: od.balliguda
    balugaon: od.balugaon
    banki: od.banki
    banpur: od.banpur
    bargarh: od.bargarh
    barbil: od.barbil
    baripada: od.baripada
    barpali: od.barpali
    basudevpur: od.basudevpur
    bellaguntha: od.bellaguntha
    belpahar: od.belpahar
    bhadrak: od.bhadrak
    bhanjanagar: od.bhanjanagar
    bhawanipatna: od.bhawanipatna
    bhuban: od.bhuban
    bijepur: od.bijepur
    binka: od.binka
    boudhgarh: od.boudhgarh
    brajrajnagar: od.brajrajnagar
    buguda: od.buguda
    champua: od.champua
    chandbali: od.chandbali
    chikiti: od.chikiti
    daspalla: od.daspalla
    deogarh: od.deogarh
    dhamnagar: od.dhamnagar
    dharamgarh: od.dharamgarh
    dhenkanal: od.dhenkanal
    digapahandi: od.digapahandi
    gudayagiri: od.gudayagiri
    ganjam: od.ganjam
    gudari: od.gudari
    gunupur: od.gunupur
    hindol: od.hindol
    hinjilicut: od.hinjilicut
    jagatsinghpur: od.jagatsinghpur
    jajpur: od.jajpur
    jaleswar: od.jaleswar
    jeypore: od.jeypore
    jharsuguda: od.jharsuguda
    joda: od.joda
    junagarh: od.junagarh
    kamakhyanagar: od.kamakhyanagar
    kantabanji: od.kantabanji
    karanjia: od.karanjia
    kashinagar: od.kashinagar
    kabisuryanagar: od.kabisuryanagar
    kendrapara: od.kendrapara
    keonjhargarh: od.keonjhargarh
    kesinga: od.kesinga
    khallikote: od.khallikote
    khandapada: od.khandapada
    khariar: od.khariar
    khariarroad: od.khariarroad
    kodala: od.kodala
    koraput: od.koraput
    kotpad: od.kotpad
    kuchinda: od.kuchinda
    malkangiri: od.malkangiri
    nayagarh: od.nayagarh
    nilgiri: od.nilgiri
    nimapara: od.nimapara
    nabarangpur: od.nabarangpur
    nuapada: od.nuapada
    odagaon: od.odagaon
    padampur: od.padampur
    paralakhemundi: od.paralakhemundi
    patnagarh: od.patnagarh
    pattamundai: od.pattamundai
    phulbani: od.phulbani
    pipli: od.pipli
    polasara: od.polasara
    purushottampur: od.purushottampur
    rairangpur: od.rairangpur
    rambha: od.rambha
    ranpur: od.ranpur
    rayagada: od.rayagada
    redhakhol: od.redhakhol
    sonepur: od.sonepur
    soro: od.soro
    surada: od.surada
    sunabeda: od.sunabeda
    tarbha: od.tarbha
    titilagarh: od.titilagarh
    tusura: od.tusura
    udala: od.udala
    umerkote: od.umerkote
    
  localitycode:
    cuttack: OTHER
    jatni: OTHER
    angul: OTHER
    choudwar: OTHER
    berhampurdevelopmentauthority: OTHER
    birmitrapur: OTHER
    berhampur: OTHER
    chatrapur: OTHER
    cuttackdevelopmentauthority: OTHER
    gopalpur: OTHER
    kalinganagardevelopmentauthority: OTHER
    khordha: OTHER
    konark: OTHER
    paradeep: OTHER
    paradipdevelopmentauthority: OTHER
    puri: OTHER
    purikonarkdevelopmentauthority: OTHER
    rajgangpur: OTHER
    rourkela: OTHER
    rourkeladevelopmentauthority: OTHER
    sambalpur: OTHER
    sambalpurdevelopmentauthority: OTHER
    sundargarh: OTHER
    talcher: OTHER
    talcherangulmeramandalidevelopmentauthority: OTHER
    vyasanagar: OTHER
    anandapur: OTHER
    aska: OTHER
    athagarh: OTHER
    athmallik: OTHER
    attabira: OTHER
    balangir: OTHER
    balasore: OTHER
    balimela: OTHER
    balliguda: OTHER
    balugaon: OTHER
    banki: OTHER
    banpur: OTHER
    bargarh: OTHER
    barbil: OTHER
    baripada: OTHER
    barpali: OTHER
    basudevpur: OTHER
    bellaguntha: OTHER
    belpahar: OTHER
    bhadrak: OTHER
    bhanjanagar: OTHER
    bhawanipatna: OTHER
    bhuban: OTHER
    bijepur: OTHER
    binka: OTHER
    boudhgarh: OTHER
    brajrajnagar: OTHER
    buguda: OTHER
    champua: OTHER
    chandbali: OTHER
    chikiti: OTHER
    daspalla: OTHER
    deogarh: OTHER
    dhamnagar: OTHER
    dharamgarh: OTHER
    dhenkanal: OTHER
    digapahandi: OTHER
    gudayagiri: OTHER
    ganjam: OTHER
    gudari: OTHER
    gunupur: OTHER
    hindol: OTHER
    hinjilicut: OTHER
    jagatsinghpur: OTHER
    jajpur: OTHER
    jaleswar: OTHER
    jeypore: OTHER
    jharsuguda: OTHER
    joda: OTHER
    junagarh: OTHER
    kamakhyanagar: OTHER
    kantabanji: OTHER
    karanjia: OTHER
    kashinagar: OTHER
    kabisuryanagar: OTHER
    kendrapara: OTHER
    keonjhargarh: OTHER
    kesinga: OTHER
    khallikote: OTHER
    khandapada: OTHER
    khariar: OTHER
    khariarroad: OTHER
    kodala: OTHER
    koraput: OTHER
    kotpad: OTHER
    kuchinda: OTHER
    malkangiri: OTHER
    nayagarh: OTHER
    nilgiri: OTHER
    nimapara: OTHER
    nabarangpur: OTHER
    nuapada: OTHER
    odagaon: OTHER
    padampur: OTHER
    paralakhemundi: OTHER
    patnagarh: OTHER
    pattamundai: OTHER
    phulbani: OTHER
    pipli: OTHER
    polasara: OTHER
    purushottampur: OTHER
    rairangpur: OTHER
    rambha: OTHER
    ranpur: OTHER
    rayagada: OTHER
    redhakhol: OTHER
    sonepur: OTHER
    soro: OTHER
    surada: OTHER
    sunabeda: OTHER
    tarbha: OTHER
    titilagarh: OTHER
    tusura: OTHER
    udala: OTHER
    umerkote: OTHER
    
  floorNo:
    ground_floor: 0
    first_floor: 1
    second_floor: 2
    third_floor: 3
    forth_floor: 4
    fifth_floor: 5
    sixth_floor: 6
    seventh_floor: 7
    eighth_floor: 8
    
    